---

- name: Copying check script
  copy: src=check_user.js dest=/home/vagrant

- name: Copying create user script
  copy: src=create_user.js dest=/home/vagrant

- name: Create MongoDB user prototype@prototype_db_dev
  command: mongo localhost:27017/prototype_db_dev /home/vagrant/create_user.js
  ignore_errors: yes

- name: Create MongoDB user prototype@prototype_db_integration_test
  command: mongo localhost:27017/prototype_db_integration_test create_user.js chdir=/home/vagrant
  ignore_errors: yes