# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "prototype-vm"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "prototype-vm"

  # Forward MongoDB port
  config.vm.network :forwarded_port, guest: 27017, host: 27017

   config.vm.synced_folder "../../../prototype-pkg", "/opt/prototype-pkg"

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM
    vb.gui = false
    vb.name = "prototype-vm"
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["modifyvm", :id,
                  "--name", "prototype-vm",
                  "--natdnshostresolver1", "on"]
  end

  config.vm.provision :shell, :inline => "echo \"Europe/Berlin\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
  config.vbguest.auto_update = false

  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'provisioning/playbook.yml'
  end

end