# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "Debian Wheezy (Vagrant base box)"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "prototype-vm"

  # Forward MongoDB port
  #config.vm.network :forwarded_port, guest: 1521, host: 1521

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM
    vb.gui = false
    vb.name = "prototype-vm"
    vb.memory = 4096
    vb.cpus = 4
    vb.customize ["modifyvm", :id,
                  "--name", "prototype-vm",
                  "--natdnshostresolver1", "on"]
  end

  config.vm.provision :shell, :inline => "echo \"Europe/Berlin\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
  config.vbguest.auto_update = false

  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'provisioning/playbook.yml'
  end

end